# GitHub: m5stickc2_base.yaml
esp32:
  board: m5stick-c
  framework: {type: arduino}
  flash_size: 8MB

substitutions:
  devicename: m5stickc-plus2
  upper_devicename: M5StickC PLUS2

spi:
  clk_pin: GPIO13
  mosi_pin: GPIO15

output:
  - platform: gpio
    id: hold_pin
    pin: {number: GPIO4, mode: OUTPUT}

display:
  - platform: ili9xxx
    model: st7789v
    id: watch_display  # The anchor ID for !extend
    cs_pin: GPIO5
    dc_pin: GPIO14
    reset_pin: GPIO12
    rotation: 90
    dimensions: {height: 240, width: 135, offset_height: 40, offset_width: 52}
    invert_colors: true
    update_interval: 150ms

i2s_audio:
  - id: bus_internal
    i2s_lrclk_pin: GPIO0
    i2s_bclk_pin: GPIO26

microphone:
  - platform: i2s_audio
    id: stickc_microphone
    i2s_audio_id: bus_internal
    i2s_din_pin: GPIO34
    adc_type: external
    pdm: true
    channel: left

speaker:
  - platform: i2s_audio
    id: media_out
    dac_type: external
    i2s_dout_pin: GPIO25

text_sensor:
  - platform: template
    id: display_text
    internal: true

select:
  - platform: template
    id: output_mode_select
    options: ["Character Mode", "Word Mode", "Full Mode"]
    optimistic: true

sensor:
  - platform: adc
    pin: GPIO38
    id: battery_voltage
    filters: [{multiply: 2.0}]
  - platform: template
    id: battery_percentage
    unit_of_measurement: "%"
    lambda: |-
      if (!id(battery_voltage).has_state()) return 0.0;
      float p = (id(battery_voltage).state - 3.0) / 1.2 * 100.0;
      return clamp(p, 0.0f, 100.0f);

color:
  - {id: my_black, red: 0%, green: 0%, blue: 0%}
  - {id: my_green, red: 0%, green: 100%, blue: 0%}

font:
  - file: "gfonts://LXGW WenKai Mono TC"
    id: font_id
    size: 18